function Api_Show(){
    let f= document.createElement('li');
    f.innerHTML='<br><br>' +
        '<p style="font-family: Font-B">Api For CapitalCompass - ObjectInfo</p>' +
        '<br><br>'
        + '<p style="font-family: Font-B">Point对象</p><br>'
        + '<p style="font-family: Font-L">常用属性[title:&lt;string&gt;]：创建Point对象时赋予的文本名称。</p><br>'
        + '<p style="font-family: Font-L">常用属性[minZoom:&lt;float&gt;]：设置地点缩放级别。</p><br>'
        + '<p style="font-family: Font-L">常用属性[CI:&lt;object&gt;](可选)：为地点设置关联词条，详细内容请参考Point.CI。</p><br>'
        + '<p style="font-family: Font-L">属性[fontSize:&lt;string&gt;]：设置文字大小，同CSS。</p><br>'
        + '<p style="font-family: Font-L">属性[fontWeight:&lt;string&gt;]：设置文字粗细，同CSS。</p><br>'
        + '<p style="font-family: Font-L">属性[contentColor:&lt;string&gt;]：设置文字色彩，同CSS。</p><br>'
        + '<p style="font-family: Font-L">属性[outlineColor:&lt;string&gt;]：设置轮廓色彩，同CSS。</p><br>'
        + '<p style="font-family: Font-L">属性[location:&lt;数组&gt;]：创建Point对象时赋予的坐标信息，可变更。</p><br>'
        + '<p style="font-family: Font-L">属性[pointSize:&lt;number&gt;]：为Point对象设置点大小(默认4)。</p><br>'
        + '<br>'
        + '<p style="font-family: Font-B">属性[<span style="font-family: Font-B;color: #4a45c0">Point</span>.CI:&lt;object&gt;]</p><br>'
        + '<p style="font-family: Font-L">属性[Title:&lt;string&gt;]：词条标题。</p><br>'
        + '<p style="font-family: Font-L">属性[ConciseIntroduce:&lt;string&gt;]：词条简要介绍。</p><br>'
        + '<p style="font-family: Font-L">属性[Url:&lt;object&gt;](可选)：为词条设置词条主页，详细内容请参考Point.CI.Url。</p><br>'
        + '<p style="font-family: Font-L">属性[For:&lt;string&gt;]：为词条设置关联项(词条所属于？)，详细内容请参考Point.CI.For。</p><br>'
        + '<br>'
        + '<p style="font-family: Font-B">属性[<span style="font-family: Font-B;color: #4a45c0">Point.CI</span>.Url:&lt;object&gt;]</p><br>'
        + '<p style="font-family: Font-L">属性[Name:&lt;string(Point_RegisterName)&gt;]：注册词条名称(请与地点注册名保持一致)。</p><br>'
        + '<p style="font-family: Font-L">属性[Introduce:&lt;string&gt;]：词条介绍。</p><br>'
        + '<p style="font-family: Font-L">属性[Date:&lt;string&gt;]：词条编辑日期。</p><br>'
        + '<p style="font-family: Font-L">属性[OriginalWriter:&lt;string&gt;]：词条创立者。</p><br>'
        + '<p style="font-family: Font-L">属性[Main:&lt;数组&gt;]：词条内容，详细内容请参考Point.CI.Url.Main</p><br>'
        + '<p style="font-family: Font-L">属性[Hashtag:&lt;string&gt;]：词条关键词。</p><br>'
        + '<br>'
        + '<p style="font-family: Font-B">属性[<span style="font-family: Font-B;color: #4a45c0">Point.CI</span>.For:&lt;string&gt;]</p><br>'
        + '<p style="font-family: Font-L">本属性用于为词条Point.CI设置收录信息，可放入CSS标准色彩，或放入指定关键词。</p><br>'
        + '<br>'
        + '<p style="font-family: Font-B">属性[<span style="font-family: Font-B;color: #4a45c0">Point.CI.Url</span>.Main:&lt;数组&gt;]</p><br>'
        + '<p style="font-family: Font-L">本属性用于提供Point.CI.Url创建词条主页时所需要的信息，数组内只能被放入对象。</p><br>'
        + '<p style="font-family: Font-L">本属性被放入的对象通常包含键值：{Type:&lt;string&gt;}与{Content:&lt;string&gt;}</p><br>'
        + '<p style="font-family: Font-L">类型[Main,Content:&lt;string&gt;]：基础文本。</p><br>'
        + '<p style="font-family: Font-L">类型[Title,Content:&lt;string&gt;]：基础标题。</p><br>'
        + '<p style="font-family: Font-L">类型[Image,Content:&lt;string(图像来自内容根的路径)&gt;]：基础图片。</p><br>'
        + '<p style="font-family: Font-L">类型[Audio,Content:&lt;string(嵌入代码)&gt;]：基础声音。</p><br>'
        + '<p style="font-family: Font-L">类型[br]：基础换行。当类型为“br”时，可忽略Content键值。</p><br>'
        + '<p style="font-family: Font-L">类型[Hashtag,Content:&lt;数组&gt;]：基础关键词。</p><br>'
    document.getElementById('Main_list').appendChild(f);
}