var publicInfo={
    ONDE_Ent:{
            Name:'Point_ONDE_Ent_Bellesh',
            Introduce:'',
            Date:'2022/11/03',
            OriginalWriter:'ONDE Entertainment',
            Main:[
                {type:'Image',Content:'/Css/TestImg/ONDE_Ent.jpg',},
                {type:'Title', Content:'Light up tones - ONDE Ent.',},
                {type:'Main', Content:'创立于现代第二阶段，被评为“首都三大经济公司”之一。ONDE Entertainment全称“ON Entertainment of Dai East”，是京川ON Ent.旗下子公司。包含媒体制作、艺人培训、偶像包装等常规经济娱乐公司服务版块，同时拥有出色的工业化音乐制作流水线。',},
                {type: 'br'},
                {type: 'Audio',Content: '<iframe allow="autoplay *; encrypted-media *;" frameborder="0" height="150" style="width:100%;max-width:660px;overflow:hidden;background:transparent;" sandbox="allow-forms allow-popups allow-same-origin allow-scripts allow-storage-access-by-user-activation allow-top-navigation-by-user-activation" src="https://embed.music.apple.com/cn/album/nasa/1450330588?i=1450330595"></iframe>'},
                {type: 'br'},
                {type: 'Main',Content: '旗下艺人：————————'},
                {type: 'Main',Content: 'ONDE Ent.是如今全港市娱乐圈三大公司之一，但刚成立时，所属艺人的成绩却十分不理想。那时京川正值政权更替，经济受影响下滑严重，母公司不愿在项目中投入更多的资金。一系列原因导致公司甚至无力承担用地年租，面临倒闭，公司地址也被迫从著有“娱乐圈一号车站”之称的时代路搬到图各瓦山。时隔一年，公司推出童星艺人“安巧儿”，并发布试水单曲《Night Alone》，初获反响。年中趁热打铁，发布迷你专辑《I’ll be Butterfly》，被大港艺赏提名“最佳新人”。次年，安巧儿在“每日8点前必须结束行程”的情况下参与拍摄影视剧《Guest》，由此开始演艺生涯。安巧儿的出道成为了公司发展史上的转捩点，单凭正规专辑《Light Tone Up》的销售额就为公司盖下了位于彼利什路的新录音室。现代第三阶段，ONDE Ent.推出新艺人团体，公司地址也重回时代路。年末安巧儿受邀出席大港艺赏内场舞台，公司被评为“首都三大经济公司”之一。'},
                {type: 'br'},
                {type:'Hashtag',Content: ['ONDE Entertainment','ON Ent.(全港)']},
            ],
            Hashtag:'',
    }
}

var pointInfo={
    Point_ChinSwee_Temple:{
    Title:'Episode：清水',
        ConciseIntroduce:'关于清水寺一家传承的故事，清水寺是跨时代前，皇室出游芝山时所修筑的庙宇。',
    Url:{
    Name:'Point_ChinSwee_Temple',
        Introduce:'',
        Date:'2022/11/10',
        OriginalWriter:'遗失在双庭的笔记簿',
        Main:[
        {type:'Main', Content:'内容待填充。',},
        {type:'Hashtag',Content: ['深游全港','遗失在芝港的笔记簿']}
    ],
        Hashtag:'',
},
    For:'Episode：Chin Swee',
},
    Point_Gutyan_TemplePack:{
        Title:'记忆中的“裕斐妈妈”是什么样的？',
        ConciseIntroduce:'游憩廟堂公园，在树林与瀑布中发现“裕斐妈妈”的踪迹。',
        Url:{
            Name:'Point_Gutyan_TemplePark',
            Introduce:'',
            Date:'2022/9/30',
            OriginalWriter:'首都公式建议',
            Main:[
                {type:'Main', Content:'关于廟堂公园：',},
                {type:'Main', Content:'廟堂公园是南天际地区一座狭长的城市森林公园，包括蒜薹街与一些花卉市场在内，是本地最热门的公园休闲场所。廟堂公园因特色的热带山水而吸引游客前往，园内种植了各种灌木、攀缘植物与多年生植物。在公园的正中心，有一座名为“贾人祠”的淡紫色寺庙，这是传说中埋葬“贾田公子”与“裕斐妈妈”的地方，被本地人视为精神圣地。在寺庙的附近坐落着一座小型瀑布，瀑布的水来自地下，当地人称之为“金钱泉”。廟堂公园树木荫蔽，是避暑的风水宝地，夏季走在公园里，能清楚地感受到迎面而来的冰爽雾气。',},
                {type:'Audio',Content:'<iframe allow="autoplay *; encrypted-media *;" frameborder="0" height="150" style="width:100%;max-width:660px;overflow:hidden;background:transparent;" sandbox="allow-forms allow-popups allow-same-origin allow-scripts allow-storage-access-by-user-activation allow-top-navigation-by-user-activation" src="https://embed.music.apple.com/cn/album/sax-on-the-beach/1439587224?i=1439587226"></iframe>'},
                {type: 'br'},
                {type:'Main', Content:'在廟堂公园中，寻找关于“裕斐妈妈”的记忆：',},
                {type:'Main', Content:'涯边善女——是人们对她的赞称。相传在旧时代，在任何拜访贾田的访客，都能因热心的裕斐妈妈而留下深刻的回忆。曾与贾田公子一同工作的渔农如是评价：“她独立且自强，性格向来和善。仅是目睹那般笑容，或感受到那股热情便能使大家的矛盾化解。”',},
                {type:'Audio',Content:'<iframe allow="autoplay *; encrypted-media *;" frameborder="0" height="150" style="width:100%;max-width:660px;overflow:hidden;background:transparent;" sandbox="allow-forms allow-popups allow-same-origin allow-scripts allow-storage-access-by-user-activation allow-top-navigation-by-user-activation" src="https://embed.music.apple.com/cn/album/summa-time/1435849207?i=1435849475"></iframe>'},
                {type:'Main', Content:'裕斐妈妈是旧时代贾田地区独立女性的代表人物，后代人之所以将裕斐妈妈视作精神象征，这也是贾田文化中“爱和爱善”的体现。如今出行在廟堂公园，不难遇见前来纪念裕斐妈妈的游客，许多当地女孩将其视为成长的目标，松门乐宁总理评价说：“这是一个好现象”。',},
                {type: 'br'},
                {type:'Hashtag',Content: ['一周建议','漫游首都计划','首都公式']},
            ],
            Hashtag:'',
        },
        For:'收录在《未来述白》',
        Width:'20em',
    },
    Point_JadeGarden_Hall_Ru:{
        Title:'聚焦文学美:麓馆文学殿堂',
        ConciseIntroduce:'享誉盛名，这座深藏在树林深处的仿古建筑是首都文学界的骄傲。',
        Url:{
            Name:'Point_JadeGarden_Hall_Ru',
            Introduce:'',
            Date:'2022/10/14',
            OriginalWriter:'成安柚子',
            Main:[
                {type:'Main', Content:'享誉盛名，这座深藏在树林深处的仿古建筑是首都文学界的骄傲。',},
                {type:'Main', Content:'当游客徘徊于枝叶招展的麓园深处，时常会被一座古雅的暗色红砖建筑所震撼。那便是被视为“文学圣地”的麓馆文学殿堂，全港市文部厅机构所谓“首都文联”的总部所在地。',},
                {type: 'br'},
                {type: 'Audio',Content: '<iframe allow="autoplay *; encrypted-media *;" frameborder="0" height="150" style="width:100%;max-width:660px;overflow:hidden;background:transparent;" sandbox="allow-forms allow-popups allow-same-origin allow-scripts allow-storage-access-by-user-activation allow-top-navigation-by-user-activation" src="https://embed.music.apple.com/cn/album/energetic/1569282309?i=1569282316"></iframe>'},
                {type: 'br'},
                {type: 'Main',Content: '关于翡翠园：'},
                {type: 'Main',Content: '翡翠园又名“麓园(Jade Garden)”，位于江代地区東南部，是一座跨时代后建造的仿旧时代式园林，有着“深色碧珠”一称。关于翡翠园内暗色系且古今混搭的清透碧绿摆设与装点设计，在建筑圈内颇有盛名，有人说设计师成功的将古代文化融入了现代的视觉引导布局，也有人说翡翠园的布局集合了“東西方建筑之特色”，给予人极其舒适的视觉体验。该园林与周围街道从卫星上俯瞰犹如一颗镶嵌在都市之中的翡翠明珠，故称为“翡翠园”。翡翠园同时也是“首都文联”的象征，被首都范围的文学人士称为“文学界的精神圣地”，在该街区坐落着密集的“首都文联”办公与学术部门，因此，有时人们会直接用“翡翠园”三字来称呼“首都文联”。'},
                {type: 'br'},
                {type:'Audio',Content: '<iframe allow="autoplay *; encrypted-media *;" frameborder="0" height="150" style="width:100%;max-width:660px;overflow:hidden;background:transparent;" sandbox="allow-forms allow-popups allow-same-origin allow-scripts allow-storage-access-by-user-activation allow-top-navigation-by-user-activation" src="https://embed.music.apple.com/cn/album/light/1570736770?i=1570736772"></iframe>'},
                {type: 'br'},
                {type: 'Main',Content: '关于首都文联(首都文科学界联合会)：'},
                {type: 'Main',Content: '首都文联是首都公式旗下的“文科学界”盟会式机构，该机构负责统筹首都范围全部的文科学界发展与前沿学术议论会等。人们对首都文联的评价往往是“由一群陈腐的老年人组成的派对”，为了消除人们的刻板印象，现代第三阶段，首都文联正式成立“对外宣传部门”（即“首都文创中心”），并深刻展开检讨，成立并成建有关学风治理的监督部门。首都文联总部位于江代地区的翡翠园街头，首要的学术报告厅被称为“麓馆会议中心”，因为街道两旁生长着十分古老的法国梧桐，所以这里看起来常年阴暗。" 虽然这群自大的老年人面对新生事物深闭固拒，但对于坚持某些敏感问题的底线，他们却能展现出令人佩服的恪守不渝。"'},
                {type: 'br'},
                {type:'Hashtag',Content: ['京川新闻厅-云游全国','成安柚子记者','麓馆文学殿堂','首都文联']},
            ],
            Hashtag:'',
        },
        For:'收录在《未来述白》',
    },
    Point_ChisanTemple_01:{
        Title:'Episode：芝山乐宁',
        ConciseIntroduce:'误入寺廟深处，在仆人“乐乐”的引导下，体验生命中仅一次的芝山之行。',
        Url:{
            Name:'Point_ChisanTemple_01',
            Introduce:'',
            Date:'2022/11/10',
            OriginalWriter:'遗失在芝港的笔记簿',
            Main:[
                {type:'Main', Content:'内容待填充。',},
                {type:'Hashtag',Content: ['深游全港','遗失在芝港的笔记簿']}
            ],
            Hashtag:'',
        },
        For:'Episode：Lost in Chisan',
    },
    Point_AnCompany01:{
        Title:'安氏科技总部',
        ConciseIntroduce:'欢迎做客(By Ra)(o^▽^o)ﾉ',
        Url:{
            Name:'Point_AnCompany01',
            Introduce:'',
            Date:'2022/9/29',
            OriginalWriter:'Ra (o^▽^o)ﾉ',
            Main:[
                {type: 'Image',Content: '/Css/TestImg/安氏科技.PNG'},
                {type: 'br'},
                {type:'Main', Content:'这里是An Company安氏科技的总部所在地，拥有进行科研开发与试验的现代建筑群。',},
                {type:'Audio',Content:'<iframe allow="autoplay *; encrypted-media *;" frameborder="0" height="150" style="width:100%;max-width:660px;overflow:hidden;background:transparent;" sandbox="allow-forms allow-popups allow-same-origin allow-scripts allow-storage-access-by-user-activation allow-top-navigation-by-user-activation" src="https://embed.music.apple.com/cn/album/whiplash/1247335504?i=1247335804"></iframe>'},
                {type:'Main', Content:'但总部貌似不对游客开放，外来人员或记者需预约才能入内。',},
                {type:'Main', Content:'地点位于南海岸地区中部，紧邻芝港西大道与南海岸滩街。',},
                {type: 'br'},
                {type:'Hashtag',Content: ['Info By Ra','An Company安氏科技']},
            ],
            Hashtag:'',
        },
        For:'An Company安氏科技',
    },
    Point_AreaLeadersOfChisan:{
        Title:'欢迎拜访芝港区！',
        ConciseIntroduce:'全港市的政治、文化与商业中心，由于行政区位于芝山山下港埠一带，因而得名芝港区。',
        Url:'',
        For:'收录在《漫游芝山》',
        Width:'20em',
    },
    Point_AreaLeadersOfChongnin:{
    Title:'欢迎拜访空港区！',
        ConciseIntroduce:'首都东部重要的政治、文化、工商业等综合中心，是全港市空运与海运的城市大门，世界级航空枢纽所在地。',
    Url:'',
    For:'收录在《未来述白》',
    Width:'20em',
},
    Point_ChisanJiangbu:{
    Title:'芝山故事',
        ConciseIntroduce:'风景仿佛在诉说芝山的繁华史，这里是大江埗最热门的看点。',
    Url:'',
    For:'收录在《未来述白》',
},
    Point_MainTempleOfCET:{
    Title:'树下民生：榆水',
        ConciseIntroduce:'“榆木树下溪流清澈”，这里是旧时代用于向天海献祭的传统文化寺廟。',
    Url:'',
    For:'收录在《漫游芝山》',
},
    Point_Marina_Lydilia:{
    Title:'乘船游双庭',
        ConciseIntroduce:'在微风摇曳的晚春时分，在里底利亚船舶乘船观光双庭风景。',
    Url:'',
    For:'收录在《藝術時代》',
},
    Point_ONDE_Ent_Bellesh:{
    Title:'ONDE Entertainment',
        ConciseIntroduce:'京川ON(Ent.)旗下子公司。',
    Url:publicInfo.ONDE_Ent,
    For:'收录在《藝術時代》',
},
    Point_ONDE_RecordingStudio:{
    Title:'ONDE Entertainment',
        ConciseIntroduce:'ONDE娱乐公司是ON Ent.(京川)旗下子公司。',
    Url:publicInfo.ONDE_Ent,
    For:'收录在《藝術時代》',
},
    Point_RuinedTemple:{
    Title:'伤痛的回忆：北庭馆大火',
        ConciseIntroduce:'这场天灾摧毁了无数家庭，破坏了无价的文化遗产。',
    Url:'',
    For:'收录在《漫游芝山》',
},
    Point_SomonreninPark:{
    Title:'总理的痕迹',
        ConciseIntroduce:'唯一的染色人工湖泊，灵感来自于总理的画作《落日桃湖》。',
    Url:'',
    For:'收录在《漫游芝山》',
    Width:'20em',
},
    Point_ThaichiTemple:{
    Title:'旧时代建筑大赏：苔芝正寺',
        ConciseIntroduce:'屹立于涯边的古代寺庙，在无数风雨中为芝山人民带来丰收与好运。',
    Url:'',
    For:'收录在《俯见芝山》',
},
    Point_Tintown_Hurilou:{
    Title:'店主的建议',
        ConciseIntroduce:'槲栎楼没有狐狸摸，因为本店铺是民营茶舍。',
    Url:'',
    For:'收录在《俯见芝山》',
},
    Point_VisionChisan01:{
    Title:'最繁华：大芝港',
        ConciseIntroduce:'在滨江之城中迷失，或仰视旧时代的威严廟宇。',
    Url:'',
    For:'收录在《俯见芝山》',
},
    Point_YuhaiTemple:{
    Title:'Episode：烛光',
        ConciseIntroduce:'这是关于梦主的故事，相传重宁中地一带，神秘的梦主居住在毓海寺中。',
    Url:{
    Name:'Point_YuhaiTempl',
        Introduce:'',
        Date:'2022/11/10',
        OriginalWriter:'遗失在空港的笔记簿',
        Main:[
        {type:'Main', Content:'内容待填充。',},
        {type:'Hashtag',Content: ['深游全港','遗失在芝港的笔记簿']}
    ],
        Hashtag:'',
},
    For:'Episode：Candlelight',
},
    Point_YuhaiTemple_CandlelightField:{
    Title:'最梦幻：行步烛场',
        ConciseIntroduce:'据说点亮寺内烛光的每一位信者，都会得到梦主的保佑，而慷慨的梦主会将信者梦中所发生的事物带入现实。',
    Url:'',
    For:'收录在《未来述白》',
    Width:'20em'
},
    Point_QueCityPark:{
    Title:'雨吹神雀',
        ConciseIntroduce:'诞生于旧时代，传说神雀曾筑巢与此地，为人民带来天降甘霖。',
    Url:'',
    For:'收录在《俯见芝山》',
},
    Point_CapitalOfficialOfChisan:{
    Title:'全港最高都政机关',
        ConciseIntroduce:'Howdy! Welcome to Economic capital.You are now live it too choicest!',
    Url:'',
    For:'首都公式',
},
    Point_Fodaoci:{
    Title:'佛道祠：文化在融合',
        ConciseIntroduce:'佛道两家向来势不两立，设计师巧妙地以此为灵感源泉。',
    Url:'',
    For:'收录在《未来述白》',
},
    //
    C4_OldShitin:{
        Title:'芝山繁荣摇篮',
        ConciseIntroduce:'旧汐是旧时代芝山停泊船舟规模最大的码头，一直沿用到现代实物港新港建立',
        Url:'',
        For:'收录在《漫游芝山》',
    },
    C4_TideTemple:{
        Title:'潮汐寺(水廪寺)',
        ConciseIntroduce:'目睹巨浪扑打寺前水梁，向天空献上无瑕的敬意。',
        Url:'',
        For:'收录在《漫游芝山》',
    },
}